# Generated by Django 5.2.3 on 2025-06-16 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pompe',
            fields=[
                ('ID_Pompe', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Pompe', models.CharField(max_length=100)),
                ('Etat', models.CharField(default='OFF', max_length=50)),
                ('Débits', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('ID_Reservoir', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Reservoir', models.CharField(max_length=100)),
                ('Volume_Max', models.FloatField()),
                ('Volume_Disponible', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SourceEau',
            fields=[
                ('ID_Source', models.AutoField(primary_key=True, serialize=False)),
                ('Type_Source', models.CharField(max_length=50)),
                ('Nom_Source', models.CharField(max_length=100)),
                ('Adresse', models.TextField(blank=True)),
                ('Contact', models.CharField(blank=True, max_length=50)),
                ('Qualité_Eau', models.CharField(max_length=50)),
                ('Volume_Fournit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('ID_Admin', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Admin', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mot_de_passe', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ID_Client', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_Client', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Téléphone', models.CharField(blank=True, max_length=15)),
                ('Adresse', models.TextField(blank=True)),
                ('Volume_Consommé', models.FloatField(default=0.0)),
                ('Solde', models.FloatField(default=0.0)),
                ('Statut_Paiement', models.CharField(default='Non payé', max_length=50)),
                ('Actif', models.BooleanField(default=True)),
                ('Motdepasse', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('ID_Distribution', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Distribution', models.DateField()),
                ('Volume_Distribué', models.FloatField()),
                ('ID_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('ID_Pompe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pompe')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('ID_Facture', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Facture', models.DateField()),
                ('Montant_Total', models.FloatField()),
                ('Statut_Paiement', models.CharField(default='Non payé', max_length=50)),
                ('ID_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('ID_Distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='Filtration',
            fields=[
                ('ID_Filtration', models.AutoField(primary_key=True, serialize=False)),
                ('Type_Filtre', models.CharField(max_length=100)),
                ('Efficacité', models.FloatField()),
                ('Date_Dernière_Maintenance', models.DateField()),
                ('ID_Pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pompe')),
            ],
        ),
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('ID_Energie', models.AutoField(primary_key=True, serialize=False)),
                ('Type_Energie', models.CharField(max_length=50)),
                ('Production_Mensuelle', models.FloatField()),
                ('Consommation_Mensuelle', models.FloatField()),
                ('ID_Pompe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pompe')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('ID_Alerte', models.AutoField(primary_key=True, serialize=False)),
                ('Message', models.TextField()),
                ('Date_Alerte', models.DateTimeField()),
                ('Statut', models.CharField(default='Non résolu', max_length=50)),
                ('Type_alerte', models.CharField(max_length=50)),
                ('ID_Pompe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pompe')),
            ],
        ),
        migrations.AddField(
            model_name='pompe',
            name='ID_Reservoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reservoir'),
        ),
        migrations.AddField(
            model_name='reservoir',
            name='ID_Source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sourceeau'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('ID_Feedback', models.AutoField(primary_key=True, serialize=False)),
                ('Commentaire', models.TextField()),
                ('Note', models.FloatField()),
                ('Date_Feedback', models.DateField()),
                ('ID_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('Note__gte', 0), ('Note__lte', 5)), name='note_range')],
            },
        ),
    ]
